name: shufflonfinder
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - prokka>=1.14
  - hmmer>=3.3
  - emboss>=6.6
  - biopython>=1.80
  - pandas>=1.5
  - matplotlib>=3.5
  - scipy>=1.9
  - pip
  - pip:
    - dna_features_viewer>=3.1
    - -e .
